class CDMSConstants:
    time_col = 'time'
    provider_col = 'provider'
    project_col = 'project'
    platform_code_col = 'platform_code'
    platform_col = 'platform'
    code_col = 'code'
    job_id_col = 'job_id'
    time_obj_col = 'time_obj'
    year_col = 'year'
    month_col = 'month'
    observations_key = 'observations'
    lat_col = 'latitude'
    lon_col = 'longitude'
    depth_col = 'depth'
