class CDMSConstants:
    time_col = 'time'
    provider_col = 'provider'
    project_col = 'project'
    platform_code_col = 'platform_code'
    platform_col = 'platform'
    code_col = 'code'
    job_id_col = 'job_id'
    time_obj_col = 'time_obj'
    year_col = 'year'
    month_col = 'month'
    observations_key = 'observations'
    lat_col = 'latitude'
    lon_col = 'longitude'
    depth_col = 'depth'

    s3_url_key = 's3_url'
    uuid_key = 'uuid'
    ingested_date_key = 'ingested_date'
    checksum_key = 'checksum'
    file_size_key = 'file_size'
    records_count_key = 'records_count'
    job_start_key = 'job_start_time'
    job_end_key = 'job_end_time'
