/**
* The following flags can be used to control stages of the pipeline to be run.
*/
def PIPELINE_CONTROL = [
    ci_skip: false
]

pipeline {
    agent {
        node {
            label 'CAE-Jenkins2-DH-Agents-Linux'
        }
    }

    environment {
        LATEST_TAG = 'latest'
        BUILD_TAG_RAW = "build-${env.BRANCH_NAME}-${env.BUILD_NUMBER}"
        BUILD_TAG = sh(script: "echo ${env.BUILD_TAG_RAW} | tr -dc \"[A-Za-z0-9\\-\\_\\.]\"", returnStdout: true).trim() // to strip out special characters in branch name
        HOME="." /* to resolve EACCES: permission denied, mkdir '/.npm'*/
        GH4JPL=credentials("wphyo-github")
        CAE_ARTI_TOKEN=credentials("wphyo-cae-artifactory")
//         CAE_ARTI_TOKEN=credentials("wphyo-cae-artifactory-token-as-text")
        GH_TOKEN="${GH4JPL_PSW}"
        GH_URL="https://github.jpl.nasa.gov/api/v3"
//         CAE_ARTI_TOKEN=credentials("wphyo-cae-artifactory")
        ARTIFACTORY_URL="https://cae-artifactory.jpl.nasa.gov:16001"
        BUILD_LIB_NAME = 'sdap-in-situ-data-services-functions'
    }

    stages {
        // "Borrowed" from https://github.com/MarkAckert/staging-zowe-ims-plugin/blob/master/Jenkinsfile
        stage('Check for Skip CI') {
            steps {
                script {
                    def result = sh (returnStatus: true, script: 'git log -1 | grep \'.*\\[skip ci\\].*\'')
                    if (result == 0) {
                        echo '"skip ci" spotted in the git commit. Aborting...'
                        PIPELINE_CONTROL.ci_skip = true
                    }
                }
            }
        }
        stage('Build build_deployment') {
            options { retry(12) }
            when { expression { return PIPELINE_CONTROL.ci_skip == false } }
            steps {
                withDockerRegistry([url: "${ARTIFACTORY_URL}", credentialsId: "${ARTIFACTORY_CREDENTIALS}"]) {
                    sh("NAME=${BUILD_LIB_NAME} VERSION=${BUILD_TAG} make -f ci.cd/Makefile build_lambda")
                    sh("curl -H X-JFrog-Art-Api:${CAE_ARTI_TOKEN_PSW} -T ${BUILD_LIB_NAME}__${BUILD_TAG}.zip ${ARTIFACTORY_URL}/artifactory/general/gov/nasa/jpl/sdap/ideas/${BUILD_LIB_NAME}__${BUILD_TAG}.zip")
                }
                sleep(time: (1000 * 4), unit: "MILLISECONDS")
            }
        }
        stage('Build and push lambda docker') {
            when { expression { return PIPELINE_CONTROL.ci_skip == false } }
            steps {
                withDockerRegistry([url: "https://index.docker.io/v1/", credentialsId: "waiphyojpl-dockerhub"]) {
                    sh("VERSION=${BUILD_TAG} make -f ci.cd/Makefile build_lambda_push")
                }
            }
        }
        stage('Build and push docker') {
            when { expression { return PIPELINE_CONTROL.ci_skip == false } }
            steps {
                withDockerRegistry([url: "https://index.docker.io/v1/", credentialsId: "waiphyojpl-dockerhub"]) {
                    sh("VERSION=${BUILD_TAG} make -f ci.cd/Makefile build_push")
                }
            }
        }
    }

    post {
        always {
            deleteDir()
            sh("docker logout")
        }
    }
}