variable "region" {}
variable "shared_credentials_file" {}
variable "profile" {}
variable "environment" {}
variable "project" {}
variable "vpc" {}
variable "ami" {}
variable "ingest_bucket_name" {}
variable "subnet_private_1" {}
variable "subnet_private_2" {}
variable "subnet_public_1" {}
variable "subnet_public_2" {}
variable "ip_subnets" {}
variable "instance_type" {}
variable "desired_capacity" {}
variable "min_size" {}
variable "max_size" {}
variable "volume_size" {}
variable "log_retention" {}